
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Augusto Winkler\AppData\Local\Programs\Python\Python39\Scripts\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def calcular():
    valor_maquina = entry_2.get()
    vida_util = entry_3.get()
    valor_residual = entry_4.get()
    valor_laser = entry_5.get()
    vida_util_laser = entry_6.get()
    preco = entry_8.get()
    quantidade = entry_9.get()
    dias_trabalho = entry_10.get()
    horas_diarias = entry_11.get()
    despesas_operacionais = entry_12.get()
    custo_operador = entry_13.get()
    lucro_desejado = entry_14.get()

    # Verificar se alguma entrada está vazia ou não é um número válido
    if (not valor_maquina or
        not vida_util or
        not valor_residual or
        not valor_laser or
        not vida_util_laser or
        not preco or
        not quantidade or
        not dias_trabalho or
        not horas_diarias or
        not despesas_operacionais or
        not custo_operador or
        not lucro_desejado):
        print("Por favor, preencha todos os campos corretamente.")
        return

    valor_maquina = float(valor_maquina)
    vida_util = int(vida_util)
    valor_residual = float(valor_residual)
    valor_laser = float(valor_laser)
    vida_util_laser = int(vida_util_laser)
    preco = float(preco)
    quantidade = int(quantidade)
    dias_trabalho = int(dias_trabalho)
    horas_diarias = int(horas_diarias)
    despesas_operacionais = float(despesas_operacionais)
    custo_operador = float(custo_operador)
    lucro_desejado = float(lucro_desejado)

    maquina = (valor_maquina - valor_residual) / vida_util
    laser = valor_laser / vida_util_laser
    horas = dias_trabalho * horas_diarias
    materia = preco / quantidade
    despesas = despesas_operacionais + custo_operador
    valor_hora = (maquina + laser + materia + despesas) / horas
    lucro = lucro_desejado * valor_hora / 100
    print(valor_maquina,vida_util,valor_residual,valor_laser,vida_util_laser)




window = Tk()


window.geometry("753x526")
window.configure(bg = "#343434")


canvas = Canvas(
    window,
    bg = "#343434",
    height = 526,
    width = 753,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    163.0,
    11.0,
    anchor="nw",
    text="Calculadora Laser CNC",
    fill="#C9C6B9",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    198.0,
    490.0,
    anchor="nw",
    text="Criado e Desenvolvido por: Augusto Winkler.",
    fill="#C9C6B9",
    font=("Inter", 12 * -1)
)

canvas.create_rectangle(
    53.0,
    291.0,
    696.0,
    294.00005531311035,
    fill="#D3A753",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    196.0,
    85.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=56.0,
    y=76.0,
    width=280.0,
    height=16.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    267.5,
    147.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=199.0,
    y=138.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    58.0,
    140.0,
    anchor="nw",
    text="Valor Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    267.5,
    174.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=199.0,
    y=165.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    58.0,
    167.0,
    anchor="nw",
    text="Vida Util:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    266.5,
    203.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=198.0,
    y=194.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    57.0,
    196.0,
    anchor="nw",
    text="Valor Residual:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    266.5,
    230.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=198.0,
    y=221.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    57.0,
    223.0,
    anchor="nw",
    text="Valor Laser:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    266.5,
    257.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_6.place(
    x=198.0,
    y=248.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    57.0,
    250.0,
    anchor="nw",
    text="Vida Util:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=56.0,
    y=104.0,
    width=128.0,
    height=24.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=208.0,
    y=103.0,
    width=128.0,
    height=24.0
)



entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    267.5,
    389.0,
    image=entry_image_8
)
entry_8 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_8.place(
    x=199.0,
    y=380.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    58.0,
    382.0,
    anchor="nw",
    text="Material:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    267.5,
    416.0,
    image=entry_image_9
)
entry_9 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_9.place(
    x=199.0,
    y=407.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    58.0,
    409.0,
    anchor="nw",
    text="Preço:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    266.5,
    445.0,
    image=entry_image_10
)
entry_10 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_10.place(
    x=198.0,
    y=436.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    57.0,
    438.0,
    anchor="nw",
    text="Quantidade:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=56.0,
    y=346.0,
    width=128.0,
    height=24.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=208.0,
    y=345.0,
    width=128.0,
    height=24.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    627.5,
    85.0,
    image=entry_image_11
)
entry_11 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_11.place(
    x=559.0,
    y=76.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    418.0,
    78.0,
    anchor="nw",
    text="Dias Trabalho:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    627.5,
    112.0,
    image=entry_image_12
)
entry_12 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_12.place(
    x=559.0,
    y=103.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    418.0,
    105.0,
    anchor="nw",
    text="Horas Diárias:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    626.5,
    141.0,
    image=entry_image_13
)
entry_13 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_13.place(
    x=558.0,
    y=132.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    417.0,
    134.0,
    anchor="nw",
    text="Despesas Operac:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    626.5,
    168.0,
    image=entry_image_14
)
entry_14 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_14.place(
    x=558.0,
    y=159.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    417.0,
    161.0,
    anchor="nw",
    text="Custo Operador:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    626.5,
    195.0,
    image=entry_image_15
)
entry_15 = Entry(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_15.place(
    x=558.0,
    y=186.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    417.0,
    188.0,
    anchor="nw",
    text="Lucro Desejado:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    627.5,
    343.0,
    image=entry_image_16
)
entry_16 = Text(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_16.place(
    x=559.0,
    y=334.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    418.0,
    336.0,
    anchor="nw",
    text="Hora Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    627.5,
    370.0,
    image=entry_image_17
)
entry_17 = Text(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_17.place(
    x=559.0,
    y=361.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    418.0,
    363.0,
    anchor="nw",
    text="Minuto Máquina:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    626.5,
    399.0,
    image=entry_image_18
)
entry_18 = Text(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_18.place(
    x=558.0,
    y=390.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    417.0,
    392.0,
    anchor="nw",
    text="Lucro Estimado:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    626.5,
    426.0,
    image=entry_image_19
)
entry_19 = Text(
    bd=0,
    bg="#C9C5B9",
    fg="#000716",
    highlightthickness=0
)
entry_19.place(
    x=558.0,
    y=417.0,
    width=137.0,
    height=16.0
)

canvas.create_text(
    417.0,
    419.0,
    anchor="nw",
    text="Valor Total:",
    fill="#FFFFFF",
    font=("Inter", 14 * -1)
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: calcular(),
    relief="flat"
)
button_5.place(
    x=418.0,
    y=228.0,
    width=278.0,
    height=44.875
)
window.resizable(False, False)
window.mainloop()
